version: '2.4'

services:
  server:
    image:
      csrf-server
    environment:
      DB_CONNECTION_URL=mongodb://db/test
    depends_on:
      db:
  db:
    image:
      mongo:4.0.10-xenial

        